var annotated_dup =
[
    [ "ogl", null, [
      [ "BoneInfo", "structogl_1_1BoneInfo.html", "structogl_1_1BoneInfo" ],
      [ "BufferObject", "structogl_1_1BufferObject.html", null ],
      [ "Camera", "structogl_1_1Camera.html", null ],
      [ "Model", "structogl_1_1Model.html", null ],
      [ "ModelAttr", "structogl_1_1ModelAttr.html", "structogl_1_1ModelAttr" ],
      [ "ModelAttrs", "classogl_1_1ModelAttrs.html", "classogl_1_1ModelAttrs" ],
      [ "ObjectAttrs", "structogl_1_1ObjectAttrs.html", "structogl_1_1ObjectAttrs" ],
      [ "Projection", "structogl_1_1Projection.html", null ],
      [ "RenderModel", "classogl_1_1RenderModel.html", null ],
      [ "Window", "structogl_1_1Window.html", null ],
      [ "WindowHints", "structogl_1_1WindowHints.html", null ]
    ] ],
    [ "EogllAttribBuilder", "structEogllAttribBuilder.html", "structEogllAttribBuilder" ],
    [ "EogllBufferObject", "structEogllBufferObject.html", "structEogllBufferObject" ],
    [ "EogllCamera", "structEogllCamera.html", "structEogllCamera" ],
    [ "EogllCameraMatrix", "structEogllCameraMatrix.html", "structEogllCameraMatrix" ],
    [ "EogllFramebuffer", "structEogllFramebuffer.html", "structEogllFramebuffer" ],
    [ "EogllModel", "structEogllModel.html", "structEogllModel" ],
    [ "EogllObjectAttr", "structEogllObjectAttr.html", "structEogllObjectAttr" ],
    [ "EogllObjectAttrs", "structEogllObjectAttrs.html", "structEogllObjectAttrs" ],
    [ "EogllObjectFileData", "structEogllObjectFileData.html", "structEogllObjectFileData" ],
    [ "EogllObjectFileFace", "structEogllObjectFileFace.html", "structEogllObjectFileFace" ],
    [ "EogllObjectIndex", "structEogllObjectIndex.html", "structEogllObjectIndex" ],
    [ "EogllObjectNormal", "structEogllObjectNormal.html", "structEogllObjectNormal" ],
    [ "EogllObjectPosition", "structEogllObjectPosition.html", "structEogllObjectPosition" ],
    [ "EogllObjectTexCoord", "structEogllObjectTexCoord.html", "structEogllObjectTexCoord" ],
    [ "EogllProjection", "structEogllProjection.html", "structEogllProjection" ],
    [ "EogllShaderProgram", "structEogllShaderProgram.html", "structEogllShaderProgram" ],
    [ "EogllTexture", "structEogllTexture.html", "structEogllTexture" ],
    [ "EogllVertAttribData", "structEogllVertAttribData.html", "structEogllVertAttribData" ],
    [ "EogllWindow", "structEogllWindow.html", "structEogllWindow" ],
    [ "EogllWindowHints", "structEogllWindowHints.html", "structEogllWindowHints" ]
];