/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Eogll */

#ifndef _Included_Eogll
#define _Included_Eogll
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Eogll
 * Method:    init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Eogll_init
  (JNIEnv *, jclass);

/*
 * Class:     Eogll
 * Method:    terminate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Eogll_terminate
  (JNIEnv *, jclass);

/*
 * Class:     Eogll
 * Method:    getVersionString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Eogll_getVersionString
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
