/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Window */

#ifndef _Included_Window
#define _Included_Window
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Window
 * Method:    w_create
 * Signature: (IILjava/lang/String;J)J
 */
JNIEXPORT jlong JNICALL Java_Window_w_1create
  (JNIEnv *, jclass, jint, jint, jstring, jlong);

/*
 * Class:     Window
 * Method:    w_destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_Window_w_1destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     Window
 * Method:    w_shouldClose
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_Window_w_1shouldClose
  (JNIEnv *, jclass, jlong);

/*
 * Class:     Window
 * Method:    w_setShouldClose
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_Window_w_1setShouldClose
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     Window
 * Method:    w_pollEvents
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_Window_w_1pollEvents
  (JNIEnv *, jclass, jlong);

/*
 * Class:     Window
 * Method:    w_swapBuffers
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_Window_w_1swapBuffers
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
