/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class WindowHints */

#ifndef _Included_WindowHints
#define _Included_WindowHints
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     WindowHints
 * Method:    wh_create
 * Signature: (ZZZZZZZ)J
 */
JNIEXPORT jlong JNICALL Java_WindowHints_wh_1create
  (JNIEnv *, jclass, jboolean, jboolean, jboolean, jboolean, jboolean, jboolean, jboolean);

/*
 * Class:     WindowHints
 * Method:    wh_destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_WindowHints_wh_1destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     WindowHints
 * Method:    wh_resizable
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_WindowHints_wh_1resizable
  (JNIEnv *, jclass, jlong);

/*
 * Class:     WindowHints
 * Method:    wh_decorated
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_WindowHints_wh_1decorated
  (JNIEnv *, jclass, jlong);

/*
 * Class:     WindowHints
 * Method:    wh_floating
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_WindowHints_wh_1floating
  (JNIEnv *, jclass, jlong);

/*
 * Class:     WindowHints
 * Method:    wh_maximized
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_WindowHints_wh_1maximized
  (JNIEnv *, jclass, jlong);

/*
 * Class:     WindowHints
 * Method:    wh_visible
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_WindowHints_wh_1visible
  (JNIEnv *, jclass, jlong);

/*
 * Class:     WindowHints
 * Method:    wh_focused
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_WindowHints_wh_1focused
  (JNIEnv *, jclass, jlong);

/*
 * Class:     WindowHints
 * Method:    wh_transparent
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_WindowHints_wh_1transparent
  (JNIEnv *, jclass, jlong);

/*
 * Class:     WindowHints
 * Method:    wh_create_default
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_WindowHints_wh_1create_1default
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
